@subject_area_mapping = {
  "Cancer" => ["Cancers"],
  "Cardiovascular" =>	["Cardiovascular system disorders"],	
  "Commissioning"	=> ["Commissioning"],
  "Complementary and alternative medicine" => ["Complementary and alternative therapies"],			
  "Diabetes" => ["Diabetes"],
  "Emergency and urgent care" => ["Emergency and urgent care"],		
  "Ethnicity and health" => ["Equality and Diversity"],			
  "Eyes and vision" => ["Eyes and vision"],
  "Genetic conditions" =>	["Genetics"], 			
  "Health management" =>	["Health management"],			
  "Infections"	=> ["Infections"],
  "Innovation and improvement" => ["Health management"]	,
  "Kidney diseases and male urogenitary disorders" => ["Renal and urogenital disorders"],
  "Knowledge management" =>	["Health management"],			
  "Later life" =>	["Later life"],
  "Learning disabilities" =>	["Learning disabilities"],			
  "Mental health" =>	["Mental health and illness"],	
  "Musculoskeletal" =>	["Musculo-skeletal disorders"],
  "Neurological conditions" =>	["Nervous system disorders"],	
  "Oral health" =>	["Oral and dental health"],			
  "Patient and public involvement" =>	["Patient and public involvement"],
  "Public health" =>	["Public Health"],			
  "Respiratory" =>	["Respiratory disorders"],	
  "Screening"	=> ["Screening"],
  "Skin disorders" =>	["Skin conditions"],
  "Stroke" =>	["Cardiovascular system disorders"],			
  "Supportive and palliative care" =>	["Palliative and End of Life Care", "Supportive care"]
#  "Child health" => { "" => ["x", "y"]  }
#  "ENT and audiology" => {},
#  "Gastroenterology and liver diseases" => {},
#  "National Library of Guidelines" => {},
#  "Surgery, anaesthesia, perioperative and critical care" => {}
#  "Trauma and orthopaedics" => {}
#  "Women's health" => {}
}